### ISSUE TITLE
MAC address won't show even though HASS sees the MAC address with 'bluetoothctl devices'

### ISSUE THREAD

**Issue by jonnoman** [AlexxIT/Ergomotion#2]
I have two Ergomotion ErgoSportive+ beds, I can see their MAC address on the HASS server using 'bluetoothctl devices'.
But when adding the integration, the MAC address list is empty.
The Bluetooth adapter is Sena UD100-G03, I also tried Bluetooth proxy with m5stack Atom Lite and still nothing shows in the MAC address list.

**Comment by AlexxIT** [comment]
There is also check by device name:
https://github.com/AlexxIT/Ergomotion/blob/1a5216977db66486b248846675810dfa39872f62/custom_components/ergomotion/config_flow.py#L14C9-L14C88

Is your bed controlled from a mobile app? Show screenshots

**Comment by jonnoman** [comment]
The device name starts with 'KSBT' followed by a 9 digit number and not with 'base-i4.' as appears in the code.
The 9 digit number corresponds to the bed id in the ErgoSportive app which is used to control the bed.

Here is the app's remote screenshot:
![Ergomotion ErgoSportive Remote](https://github.com/AlexxIT/Ergomotion/assets/79320504/163fdf15-0b05-424c-9748-562543471ef7)

**Comment by AlexxIT** [comment]
Show device diagnostics for bluetooth adapter.

**Comment by AlexxIT** [comment]
1. Download this app https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp (same app for iOS).
2. Show this screen - Service 0xFFE0, Char 0xFFE4

![photo_2023-12-27_12-44-16](https://github.com/AlexxIT/Ergomotion/assets/511909/f1d10e0f-4e71-4a63-a600-575855dc1e80)

**Comment by jonnoman** [comment]
Here is the device diagnostic as for the BLE info, I'll check it when I get back from work

[config_entry-bluetooth-bd133a338f17b74ff237a8345b157ab6.json.txt](https://github.com/AlexxIT/Ergomotion/files/13777779/config_entry-bluetooth-bd133a338f17b74ff237a8345b157ab6.json.txt)

**Comment by jonnoman** [comment]
I don't have such services:
![BLE](https://github.com/AlexxIT/Ergomotion/assets/79320504/a8343ec4-dbff-4491-bef7-0f4ee2a85717)

**Comment by AlexxIT** [comment]
So your bed has another hardware and software and can't be controlled via this integration

**Comment by jonnoman** [comment]
Yeah that's what I figured.
Thank you.

**Comment by menant** [comment]
Sorry to re-open this question:
I seem to be having the same problem while using a Bluetooth Proxy.
Can you help me troubleshoot?
