### ISSUE TITLE
No MAC address displayed with Bluetooth Proxy

### ISSUE THREAD

**Issue by menant** [AlexxIT/Ergomotion#4]
Running Home Assistant Yellow using an ESP32 ESPHome Bluetooth Proxy with Active mode on.
I'm trying to connect to an Ergomotion Rio 5.0 adjustable base, but there's no MAC address displayed when I launch the integration.

Please can you help me troubleshoot?

**Comment by AlexxIT** [comment]
ESPHome Bluetooth Proxy handled by Hass core. Not related to this integration.

https://github.com/AlexxIT/Ergomotion/blob/1a5216977db66486b248846675810dfa39872f62/custom_components/ergomotion/config_flow.py#L13-L14

Or you have an unsupported device. Or your proxy does not work properly with such devices.

Personally, I've had a terrible experience with ESPHome Bluetooth Proxy. I'm using a good USB stick right now.

**Comment by menant** [comment]
Alex, thank you very much for the follow-up.

I noticed that the name is meant to start with "base-i4", the name of my Ergomotion Rio 5.0 bed starts with KSBT, which I assume stands for Keeson Bluetooth.

Do you know if we could make that kind of controller compatible with your integration?

**Comment by AlexxIT** [comment]
If you have basic IT skills, you can try to capture the data that your model has. For example with
https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp

If the data is mostly the same, it won't be hard to add support.

**Comment by menant** [comment]
Thanks Alex! I created an export with all Sources and Levels.

**Comment by menant** [comment]
👉 [nRF Connect Log 20240712.txt](https://github.com/user-attachments/files/16202964/nRF.Connect.Log.20240712.txt)

Does this file contain all the data you expected to be captured?

**Comment by AlexxIT** [comment]
I can't find similar services in your log. Probably your bed has another software.

**Comment by menant** [comment]
Thanks Alex.

Anything we can try to do together so your software supports latest versions of the Ergomotion beds sold in the USA?

**Comment by AlexxIT** [comment]
I made support for these beds because I have one. Bought with my own money.
Most likely your bed has a completely different software. It is unlikely that there will be code reuse.

**Comment by menant** [comment]
Thanks for your feedback.
