### ISSUE TITLE
Модуль блютус

### ISSUE THREAD

**Issue by kot-925** [AlexxIT/Ergomotion#8]
Здравствуйте, главный вопрос где и как приобрести модуль блютус?

**Comment by AlexxIT** [comment]
Официально он нигде не продаётся. Он или должен поставляться с кроватью. Или нужно его искать на локальном китайском рынке.

**Comment by kilkams** [comment]
> Здравствуйте, главный вопрос где и как приобрести модуль блютус?

извиняюсь за сообщение в закрытую тему.
https://www.ebay.com/itm/176296855831?chn=ps&mkevt=1&mkcid=28
вот блютуз продается на ебее. у меня  на 450 модели заработал.
