### ISSUE TITLE
Атрибут effect сцены не меняется

### ISSUE THREAD

**Issue by kilkams** [AlexxIT/Ergomotion#9]
Приветствую. Огромное спасибо за проделанную работу. Ваша статья на хабре (вроде на хабре) побудила меня найти модуль для управления кроватью. Сейчас столкнулся с проблемой. я могу включить сцену и выбрать необходимую (меня интересует TV). кровать при этом принимает нужное положение, но атрибут effect: null не меняется. хотел привязать автоматизацию на это, но пока только по положению головы и ног могу. это только у меня такая проблема?

**Comment by AlexxIT** [comment]
Атрибут эффект не имеет состояния. Кровать не знает, в каком состоянии она находится. Известны только позиции головы и ног. Можете завязаться на их конкретные значения.

**Comment by kilkams** [comment]
Сделал такую автоматизацию. теперь атрибут effect меняется, даже с пульта. 
`alias: Положение кровати`
`description: ""`
`triggers:`
`  - trigger: state`
`    entity_id:`
`      - cover.хххххххххххх_foot_position`
`      - cover.хххххххххххх_head_position`
`    enabled: true`
`    attribute: current_position`
`conditions: []`
`actions:`
`  - repeat:`
`      count: 30`
`      sequence:`
`        - delay:`
`            hours: 0`
`            minutes: 0`
`            seconds: 1`
`            milliseconds: 0`
`          enabled: true`
`        - choose:`
`            - conditions:`
`                - condition: and`
`                  conditions:`
`                    - condition: state`
`                      entity_id: cover.хххххххххххх_foot_position`
`                      attribute: current_position`
`                      state: 13`
`                    - condition: state`
`                      entity_id: cover.хххххххххххх_head_position`
`                      attribute: current_position`
`                      state: 22`
`              sequence:`
`                - action: python_script.hass_entities`
`                  metadata: {}`
`                  data:`
`                    action: set_attributes`
`                    entity_id: light.хххххххххххх_scene`
`                    attributes:`
`                      - effect: tv`
`                - stop: Выполнено`
`mode: single`
